---
name: Build and Test

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Build ISO image
        uses: ./.github/actions/build
        with:
          artifact_name: arch-grit
