---
name: Build Arch-GRIT

on:  # yamllint disable-line rule:truthy
  push:
  pull_request:
    branches:
      - master

jobs:
  # Container is the build environment for the ISO
  build-container:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Repository
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}/build-env:latest

  build-iso:
    needs: build-container
    runs-on: ubuntu-latest
    steps:

      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Create out directory
        run: mkdir out

      - name: Build ISO
        run: >
          docker run --privileged
          -v $PWD:/repo
          ghcr.io/${{ github.repository }}/build-env:latest

      - name: Set ISO file variable
        run: echo "iso_file=$(ls out/*.iso)" >> $GITHUB_ENV

      - name: Calculate SHA256sum
        run: sha256sum ${{ env.iso_file }} > ${{ env.iso_file }}.sha256

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: arch-grit
          path: out/
          retention-days: 3
          if-no-files-found: error

  create-release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build-iso
    runs-on: ubuntu-latest
    steps:

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: arch-grit

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: '*'
