---
name: Build and Test

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: docker.io/koalaman/shellcheck:v0.9.0
      volumes:
        - ${{ github.workspace }}:/repo
    steps:
      - name: Lint 'profiledef.sh'
        run: shellcheck -a src/profiledef.sh

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Build ISO image
        uses: ./.github/actions/build
        with:
          artifact_name: arch-grit
