---
name: Release

on:  # yamllint disable-line rule:truthy
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Build ISO image
        uses: ./.github/actions/build
        with:
          artifact_name: arch-grit

  create-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: arch-grit

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: '*'
